// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

// ordmic

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_kappa
List rcpp_kappa(const NumericVector & v1, const NumericVector & v2);
RcppExport SEXP ordmic_rcpp_kappa(SEXP vs1, SEXP vs2) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result = Rcpp::wrap(rcpp_kappa(vs1, vs2));
    return rcpp_result;
END_RCPP
}
